version: 2

before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  -
    id: cert-manager-webhook-vultr
    env:
      - CGO_ENABLED=0

    binary: cert-manager-webhook-vultr

    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.VersionPrerelease= '

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

archives:
  -
    formats: [tar.gz]

    files:
      - none*

    format_overrides:
      - goos: windows
        formats: [zip]


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .ProjectName }}_v{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^testdata:'
      - '^deploy:'

dockers:
  - dockerfile: Dockerfile.goreleaser
    ids:
      - cert-manager-webhook-vultr
    goos: linux
    goarch: amd64
    image_templates:
      - "vultr/cert-manager-webhook-vultr:release"
      - "vultr/cert-manager-webhook-vultr:{{ .Tag }}"


release:
  draft: true
  github:
    owner: vultr
    name: cert-manager-webhook-vultr
