name: "Unit/Coverage Tests"

on: pull_request_target

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      
      - name: Setup API Key
        run: |
          KEY=$(echo -n '${{ secrets.VULTR_API_KEY }}' | base64)
          cat << EOF > testdata/vultr/api-key.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: vultr-credentials
          type: Opaque
          data:
            apiKey: "${KEY}"
          EOF

      - name: Run unit tests and coverage test
        id: test-coverage
        run: |
          TEST_ZONE_NAME=vultr-testing-os.com. make test > output.txt

      - name: Transform output
        id: results
        if: always()
        run: |
          CONTENT=$(tail output.txt)
          CONTENT="${CONTENT//'%'/'%25'}"
          CONTENT="${CONTENT//$'\n'/'%0A'}"
          CONTENT="${CONTENT//$'\r'/'%0D'}"
          echo "::set-output name=content::$CONTENT"

      - name: Add Comment
        uses: actions/github-script@v5
        if: always()
        with:
          script: |
            const output = `### Unit Tests and Coverage Results
            <details><summary>Show Output</summary>

            \`\`\`
            ${{ steps.results.outputs.content }}
            \`\`\`
            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

